title: Reportes semanales
description: Portafolio personal de Emiliano Gutiérrez

# GitHub Pages
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

url: "https://Em1l1an0gtz3.github.io/"
baseurl: "/portafolio-just-the-docs"

just_the_docs:
  custom_css:
    - "assets/css/custom.css"
  footer_content: ""

search_enabled: false

permalink: pretty

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
